version: dev.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild CK2ToEU4.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild CK2ToEU4/CK2ToEU4.vcxproj -property:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild CK2ToEU4Tests/CK2ToEU4Tests.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test: off
artifacts:
- path: Release
  name: CK2ToEU4-0.0init-prerelease
deploy:
- provider: GitHub
  release: windows_development_build
  description: Development version. Rebuilt automatically after every pull request.
  auth_token:
    secure: LBJzs4y9j0N5y0ajp7gmVk3Pvnec1UU5pTCdIMbQYUddEXQnWTJ79FXsd9SCs7YQ
  repository: paradoxGameConverters/CK2ToEU4
  artifact: CK2ToEU4-0.0init-prerelease
  prerelease: true
  force_update: true